### ISSUE TITLE
Chocolatey package?

### ISSUE THREAD

**Issue by mikepurvis** [CemraJC/em-n-en#1]
Thanks for this! I just switched back to Windows after a decade on Mac OS, and I was really missing having a convenient system-wide shortcut for en and em— this tool fit the bill perfectly, yay!

I have no idea what would be involved, but it would be great if this were installable through chocolatey: https://chocolatey.org/docs/create-packages

**Comment by digitalcoyote** [comment]
I'd be willing to make the package and add it to my AU repo (would automatically update it if needed)

**Comment by digitalcoyote** [comment]
https://chocolatey.org/packages/em-n-en

It's passed review and is now available

**Comment by mikepurvis** [comment]
Yay, thanks for this!
